### PR TITLE
feat: add Windows Terminal support

### LINKED ISSUE #35: Add Windows Terminal
Initial attempt at adding support for the [Windows Terminal](https://github.com/Microsoft/Terminal).

```json
{
  "profiles": {
    "defaults": {
      "colorScheme": "Srcery"
    }
  },

  "schemes": [
    {
      "name": "Srcery",
      "black": "#1c1b19",
      "red": "#ef2f27",
      "green": "#519f50",
      "yellow": "#fbb829",
      "blue": "#2c78bf",
      "purple": "#e02c6d",
      "cyan": "#0aaeb3",
      "white": "#D0BFA1",
      "brightBlack": "#918175",
      "brightRed": "#f75341",
      "brightGreen": "#98bc37",
      "brightYellow": "#fed06e",
      "brightBlue": "#68a8e4",
      "brightPurple": "#ff5c8f",
      "brightCyan": "#53fde9",
      "brightWhite": "#fce8c3",
      "foreground": "#fce8c3",
      "background": "#1c1b19",
      "cursorColor": "#FBB829",
      "selectionBackground": "#FCE8C3"
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by MindTooth**
~~I need to verify this in a Windows VM first.  Submitting it for now.~~ Works!

Closes #35.

### CODE REVIEW

**Comment by MindTooth** [comment]
Care to take a look and merge if okay?

**Comment by roosta** [comment]
Looks good, one minor nitpick would be that the cursor color should be yellow (#FBB829) in accordance with the other themes that let you define that.

**Comment by MindTooth** [comment]
So it seems.  Then I' used the wrong color for the blink template I did last.  Also noticed that st did have the wrong color aswell.  Care to verify?

**Comment by roosta** [comment]
Does st define a cursor color?

**Comment by MindTooth** [comment]
I'll push a fix for blink.

https://github.com/srcery-colors/srcery-terminal/blob/a299e56ecd74aa5f7f9c634d0f971b489a9f8624/st/srcery_st.c#L35

Not sure how st works, but read it as defining the cursor color.

**Comment by roosta** [comment]
You are absolutely right, just missed it. I need to do some testing but I expect that setting `defaultcs` to `3` would do it.

**Pull request merged**
