### PR TITLE
Adjust macOS Terminal.app colours

### PR DESCRIPTION
**Pull request by Sangeppato**
The colorscheme included in the repo contains the wrong colours. The Hex values are correct, but they are considered in the 'Generic RGB' color space, while they should be in the 'sRGB/Device RGB' one (you can quickly verify they're wrong checking side-by-side with iTerm2).
I've just adjusted the colour palette considering the sRGB space (I've kept the default cursor colour, since on Terminal.app there's no "smart cursor" feature, so the text would be completely unreadable if the cursor had the same colour)

### CODE REVIEW

**Comment by MindTooth** [comment]
Hi,

I believe that any changes is to done by the template system and this seems to be missing just that.

Nice contribution.  And I musk ask you to take a look at how the `bin/builder` script works for dynamically create the schema.

If you need help, just me or roosta. 🤙🏻

**Comment by Sangeppato** [comment]
Sorry, I didn't thought about the build system, obviously my commit doesn't make any sense considering it..

Anyway, I had a look at a Terminal.app profile using sRGB and it appears overly complicated. Trying to decode a simple colour using a base64 decoder I got something like this: 
Screenshot 2019-11-14 at 12 59 41

I would say this is not really worth anyone's time.

Changing the color space to "Device RGB" and then setting the HEX also does the trick, but it looks like Terminal.app just tweaks the R,G,B values in the plist file, so I don't think this would be possible to implement.

At this point, maybe it would be better to add a note in the README saying that the Terminal.app colours are be quite a bit off due to Apple's stupid approach?
I'm going to maintain a manually generated profile for Terminal.app anyway, it looks like the only way to me.

(BTW, congratulations for both the amazing colorscheme and the clean implementation, they're by far the best I've ever seen!)

**Comment by MindTooth** [comment]
Too bad that there is not an easy way to solve this.  At least you tried. :smile:

Thank you for your contribution!

**Comment by roosta** [comment]
When I made the builder script the whole Terminal.app portion of the script is more or less copy paste from source found [here](https://github.com/stayradiated/termcolors/blob/ecce5b7781f7d77bb73d7c4d26284b02d3bb4ade/lib/formats/terminal-app.js#L83). I don't know how or why it works, but shouldn't it be possible to generate a palette using the right colorspace? @Sangeppato how'd you generate the config for this pull request?

**Comment by roosta** [comment]
I'll add a note to the readme if this just isn't doable, shame though. Would like it to work properly across the board.

**Comment by Sangeppato** [comment]
Terminal.app's profiles are quite weird compared to others with their whole base64 thing. 
Terminal.sexy's profiles use the "Generic RGB" colorspace as well (causing wrong colors).
sRGB looks quite complex to generate to me, maybe it woukd be possible with 'Device RGB', I'll try to have a look at it again but I didn't find much documentation about it

**Pull request closed without merging**
