### PR TITLE
feat: add basic color terminal previewer

### PR DESCRIPTION
**Pull request by MindTooth**
Something that I threw together so that I could preview the colors in a terminal.  Wanted it since I'm adding some plugin schemas to the Vim.

Can of course be improved. 😅

Screen Shot 2020-07-10 at 13 45 45

### CODE REVIEW

**Comment by MindTooth** [comment]
Screen Shot 2020-07-10 at 15 13 59

Added the name as well. 😛

**Comment by roosta** [comment]
Love it :) an option to print indexes, hexes and rgbs would be really cool too.

**Comment by MindTooth** [comment]
I can add a verbose flag or something.  Very rudimentary so far.

**Comment by MindTooth** [comment]
Screen Shot 2020-07-12 at 00 36 09

Need some help on the desired output.  Maybe use a library for writing tables?

https://github.com/jedib0t/go-pretty#table

**Comment by roosta** [comment]
A table would be pretty sweet. It wasn't my intention to add to your workload on this, merely a suggestion. Feel free to merge at any point.

**Comment by MindTooth** [comment]
Screen Shot 2020-07-12 at 15 33 52

Thoughts?

**Comment by roosta** [comment]
Looks fantastic, gonna be a great addition to this repository.

**Pull request merged**
