### PR TITLE
Add colour scheme for Tilix

### PR DESCRIPTION
**Pull request by davidnash**
[Tilix](https://gnunn1.github.io/tilix-web/)

### CODE REVIEW

**Comment by davidnash** [comment]
This is my first github PR - please let me know if there's any issues.

**Comment by roosta** [comment]
Thank you for your contribution. A few nitpicks:
* Theme name is spelled wrong
* Please add a comment to the theme, use "Color scheme with clearly defined contrasting colors and a slightly earthy tone."
* The background color is not right, it should be black (#1C1B19)
* Ideally the cursor color should be yellow (#FBB829) with black foreground (#1C1B19) (this isn't consistently set in the other themes yet, but it is what is used in the vim and emacs themes)

**Comment by davidnash** [comment]
Okay, done! (The misspelled theme name was particularly embarrassing!)

**Comment by roosta** [comment]
Thanks :)

**Comment by roosta** [comment]
One final change, in keeping with the rest of the themes could you rename the theme to `srcery_tilix.json`?

**Pull request merged**
