### PR TITLE
Feat/refactor - new template engine, use new palette package

### LINKED ISSUE #12: Colors look different between Terminal.app and Alacritty.
So, I've setup both Terminal.app and Alacritty with the srcery colorscheme. And I noticed that the colors don't look identical. I took some screenshots to show this:

Terminal.app with Srcery colorscheme:
terminal

Alacritty with Srcery colorscheme:
alacritty

I wasn't exactly sure why this would be. I checked the settings and confirmed that both are set correctly. For example, for the red color, Terminal.app is set to `#EF2F27`, and Alacritty is set to `0xEF2F27`. So that should be identical. But it's not. I had a hunch that it has something to do with color correction, so I used the Apple Digital Colour Meter to check.

Terminal.app renders Generic RGB 239, 47, 39.
alacritty_color

Alacritty renders 239, 47, 39 as Display Native Value.
terminal_color

This is why they look different, I'm guessing that Alacritty doesn't perform color correction. I'm not sure if that is a bug or a feature. But maybe the configs have to be adjusted slightly? I might manually perform color correction and pop the correct values into Alacritty so it's more consistent. Just leaving this here in case anyone else notices.

### PR DESCRIPTION
**Pull request by roosta**
## Refactor
I refactored most of the codebase, I decided to change the template engine to handlebars, dropping termcolor. Handlebars is a lot more flexible to work with.

I changed all the templates to handlebars syntax, and redid most of the builder, simplifying in the process.

Every config was made sure exported identical, except for terminal.app

### terminal.app

I had to drop support for terminal.app, there isn't any good way of programmatically generate a proper srgb palette. `terminal.app` is expecting some base64 nonsense, and I was never happy with the magic numbers/copy pasta of that particular config, so I dropped it.

Closes #12 

### README generation

I've moved the readme to a template as well, serving as an example of how to generate readme tables using the new [palette package](https://github.com/srcery-colors/srcery-palette/pkgs/npm/srcery-palette)

### Tooling

We should probably setup some sort of build action, I've not had time to look at that yet, or considered the implementation, but I expect a default make would do, checking for changes maybe. No decent way of testing this, but just checking that the build goes through could go a long way.

I've also removed the install rule from the make file, instead creating a rule `node_modules` so installing should happen automatically.

Feedback appreciated :)

### CODE REVIEW

**Comment by MindTooth** [comment]
Nice job!  Do like the helpers in Handlebars.  So simple, yet so powerful.

Also, having the colors in a package and being able to reference different formats, is perfect. 👌🏻

**Review by MindTooth — APPROVED** [review]

**Comment by roosta** [comment]
Thanks @MindTooth :) You thinking squash merge here? The commit history doesn't give you very good snapshots for debugging, and all those fix commits only apply to the refactor.

**Comment by MindTooth** [comment]
> Thanks @MindTooth :) You thinking squash merge here? The commit history doesn't give you very good snapshots for debugging, and all those fix commits only apply to the refactor.

Squash in WebUI resets your signatures.  So, it’s up to you. 😉  But, some sort of squashing is better.

**Comment by roosta** [comment]
Alright, screw it, I'll just merge, worts and all.

**Comment by roosta** [comment]
Doesn't seem like signing squash merge when your the author is a problem:
> GitHub will automatically use GPG to sign commits you make using the GitHub web interface, except for when you squash and merge a pull request that you are not the author of.
- source: https://github.com/github/docs/issues/11081#issue-1022691663

**Comment by roosta** [comment]
Well, it signed the commit with something, but I'm not sure which key, but not my personal one. Oh well. Good to know going forward.

**Pull request merged**
