### PR TITLE
Srcery config builder

### PR DESCRIPTION
**Pull request by roosta**
Managed to cobble together a config generator that uses [termcolors](https://github.com/stayradiated/termcolors). 

Essentially I've made a `palette.json`, and templates for all the configs, a `bin/builder` node script that uses termcolor and outputs generated config to stdout. There's also a Makefile that is the main interface for generating new configs if the templates or palette was changed.

Any feedback or changes is appreciated. See readme for instructions.

### CODE REVIEW

**Comment by MindTooth** [comment]
Ohh.  I had sent an email replying to this thread, bu t it’s nowhere to be found. 🤔 

I detect som color change for cursor?  Is this a result of outdated schemes?

Other then that, it is a really nice job.  I guess you had the time this summer? :smile:

**Comment by roosta** [comment]
Yeah the cursor change was due to outdated configs. Thanks for the feedback :) Yeah I managed to squeeze in some time on the tail end of summer :)

**Comment by MindTooth** [comment]
Is every implementation covered by your script?

**Comment by roosta** [comment]
Should be, it's possible I've missed one but I dont think so

**Pull request merged**
